# Generated by Django 3.1.7 on 2021-03-23 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='0', max_length=1000)),
                ('hed1', models.CharField(default='0', max_length=1000)),
                ('p1', models.CharField(default='0', max_length=5000)),
                ('hed2', models.CharField(default='0', max_length=1000)),
                ('p2', models.CharField(default='0', max_length=5000)),
                ('hed3', models.CharField(default='0', max_length=1000)),
                ('p3', models.CharField(default='0', max_length=5000)),
                ('image', models.ImageField(upload_to='blog/blogimages')),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
